apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-test-${version}
  name: go-test-${version}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-test
    spec:
      containers:
      - image: 10.168.0.76:9000/repository/dev-registry/go@sha256:0d733ed42d625c5c9d199c97a656d32fc7493c71ceb262f3446941f4b6aeab69
        name: go
        resources: {}
      imagePullSecrets:
      - name : nexus-secret
status: {}