apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: go-route-${version}
  namespace: pod-test
  labels:
    app: "go-test-${version}"
spec:
  path: /
  to:
    kind: Service
    name: go-service-${version}
  port:
    targetPort: 8080