apiVersion: v1
kind: Service
metadata:
  name: go-service-${version}
  namespace: pod-test
spec:
  selector:
    app: go-test-${version}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
